### ISSUE TITLE
Doesn't seem to be working with Leaflet 1.2.0

### ISSUE THREAD

**Issue by arelenglish** [henrythasler/Leaflet.Geodesic#29]
I can get it working fine with the 1.0.1, but it doesn't seem to be working with 1.2.0. No errors in the console, just fails silently. I'm using GeoJSON.

**Comment by henrythasler** [comment]
I can confirm this issue. Investigating...

**Comment by henrythasler** [comment]
Root cause: ES6 does not allow overwriting of existing class members (rough explanation).

I have created a testing branch to address this issue. You can check it out if you like. The implementation for geojson has changed completely. See geojson.html in the example folder. I will do more testing and cleanup in the next days and then merge with master.

**Comment by arelenglish** [comment]
Will take a look tonight. Thanks for working on this!
