### ISSUE TITLE
Filling a circle

### ISSUE THREAD

**Issue by samipuro** [henrythasler/Leaflet.Geodesic#35]
[enhancement request]

Hi,

This plugin is really helpful for us, but one crucial feature is missing.. Or then I am just missing how to use it ;)

Namely the ability to **fill** a geodesic circle with a certain/defined color, in a similar manner like a normal circle can be filled in Leaflet's normal circle function (opacity and color for the fill).

**Comment by henrythasler** [comment]
That sounds like a good idea. I will have a look what needs to be modified.

**Comment by henrythasler** [comment]
LOL. No changes needed at all because it is already supported: just set `fill: true`
```
var Geodesic3 = L.geodesic([], {
	weight:3,
	opacity:1,
	fill: true,
	color: 'green',
	steps: 40
}).addTo(map);

Geodesic3.createCircle(calgary, 2000000);
```
I will add this info to the readme and the examples.

**Comment by henrythasler** [comment]
I'm not sure what can be done about that. Let me think for a while.

**Comment by henrythasler** [comment]
I will address this issue during refactoring (#40) that is currently in progress.

**Comment by henrythasler** [comment]
This is fixed with v2.1.0+.

**Comment by jziggas** [comment]
Terrific news, thanks @henrythasler !

**Comment by jziggas** [comment]
Ah, I am realizing we were using the ES5 branch but the recent changes are only applied to master. Is there any plan to update the ES5 branch at this point?

**Comment by henrythasler** [comment]
The toolchain creates distributions in the following formats:

- `cjs` - CommonJS, suitable for Node and other bundlers) `dist/leaflet.geodesic.js`
- `esm` - Keep the bundle as an ES module file, suitable for other bundlers and inclusion as a <script type=module> tag in modern browsers `dist/leaflet.geodesic.esm.js`
- `umd` - Universal Module Definition `dist/leaflet.geodesic.umd.min.js`

I haven't fully understood the differences but can you please check the [dist-folder](https://www.jsdelivr.com/package/npm/leaflet.geodesic?path=dist). I'm pretty sure there is something for your needs. Otherwise, please describe exactly what you need to do.

**Comment by jziggas** [comment]
Will do, thanks for the note. Going to investigate using master first and just dropping support for IE11 :)

**Comment by henrythasler** [comment]
Yeah. [Nobody uses IE11](https://www.w3schools.com/browsers/browsers_explorer.asp) anyway.
