### ISSUE TITLE
Import issue?

### ISSUE THREAD

**Issue by jziggas** [henrythasler/Leaflet.Geodesic#47]
In the README it says there is a function called `setLatLng` for updating the geometry of a circle. I am getting an error in my code `setLatLng is not a function`. It seems like the object is a Polyline even though I am trying to make a GeodesicCircle. It appears `setRadius` is missing as well.

I have my own `leaflet.d.ts` with the following:

```
// leaflet.d.ts
...
import 'leaflet.geodesic/dist';
...
declare module 'leaflet' {
  // some custom extensions
}
```

And in a generic app imports file:
```
import 'leaflet';
...
// Some other leaflet plugins
import 'leaflet.geodesic';
```
And then in the map code:

```
let latestDesyCircle: L.GeodesicCircle;
...
latestDesyCircle = L.geodesiccircle(_latLng, {
  ...params,
  radius: radius,
});
latestDesyCircle.setRadius(radius);
```

![image](https://user-images.githubusercontent.com/1485767/68704738-c8116480-055a-11ea-994d-02cbd6a3900a.png)

Using Webpack.

**Comment by henrythasler** [comment]
You definitely need to use `setLatLng(latlng: L.LatLngExpression)` and `setRadius(radius: number)`. I just clarified that in the README.

`GeodesicCircleClass` uses `L.Polyline` internally, so this is also ok.

I could only guess, that the type definitions are somehow incorrect due to the module declarations that leaflet uses and leaflet.geodesic plugs into. I need to investigate that in detail. 

Is that an angular app or how do you develop your app?

**Comment by jziggas** [comment]
Well, this is embarrassing. I just found an old piece of code somewhere else that was calling the old `L.geodesic(...)` from the ES5 branch which I think initially generated a Polyline and that's why the browser complained when I tried to update radius later. So the issue seems to be entirely my own fault, sorry! Yes it is an Angular app with a Leaflet map, several plugins, and some custom logic. Closing for now.
